  idpconf_entityid: 'https://tunnistaminen.test/idp2'
  idpconf_displayname: "KaPA DEV IdP"
  idpconf_displayname_fi: "KaPA DEV IdP fi"
  idpconf_displayname_en: "KaPA DEV IdP en"
  idpconf_displayname_sv: "KaPA DEV IdP sv"
  idpconf_description: "KaPA DEV IdP"
  idpconf_description_fi: "KaPA DEV IdP desc fi"
  idpconf_description_en: "KaPA DEV IdP desc en"
  idpconf_description_sv: "KaPA DEV IdP desc sv"
  idpconf_kapa_image_url: "https://{{ ext_router_host }}/static/img/kapa.png"
  idpconf_organisation_name: "KaPA e-identification development"
  idpconf_organisation_name_fi: "KaPA e-identification development fi"
  idpconf_organisation_name_en: "KaPA e-identification development en"
  idpconf_organisation_name_sv: "KaPA e-identification development sv"
  idpconf_organisation_displayname_fi: "KaPA e-identification development desc fi"
  idpconf_organisation_displayname_en: "KaPA e-identification development desc en"
  idpconf_organisation_displayname_sv: "KaPA e-identification development desc sv"
  idpconf_contact_given_name: "KaPA e-identification development"
  idpconf_contact_surname: "KaPA e-identification development"
  idpconf_contact_email: "admin@tunnistaminen.test"
  idpconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ ext_router_host }}"
  shibgen_idp_id: "pub_core_idp"
  idpconf_access_allowed_ip_range: "\"#{ {'192.168.0.1/32', '::1/128'} }\""
  katso_global_logout_url: 'https://htesti.katso.tunnistus.fi/uas/logout'
