---
#Common
#Identity Provider
  idpconf_access_allowed_ip_range: "\"#{ {'192.168.0.1/32', '::1/128'} }\""
  idpconf_keystore_pass: '{{ mobile_idp_keystore_pass_value }}'
  idpconf_sealer_storepass: '{{ mobile_idp_sealer_keystore_pass_value }}'
  idpconf_sealer_keypass: '{{ mobile_idp_sealer_keystore_pass_value }}'
  idpconf_displayname: "Kapa dev Mobile IdP"
  idpconf_displayname_fi: "Kapa dev Mobile IdP fi"
  idpconf_displayname_en: "Kapa dev Mobile IdP en"
  idpconf_displayname_sv: "Kapa dev Mobile IdP sv"
  idpconf_description: "Kapa dev Mobile IdP"
  idpconf_description_fi: "Kapa dev Mobile IdP desc fi"
  idpconf_description_en: "Kapa dev Mobile IdP desc en"
  idpconf_description_sv: "Kapa dev Mobile IdP desc sv"
  idpconf_organisation_name: "Kapa development"
  idpconf_organisation_name_fi: "Kapa development fi"
  idpconf_organisation_name_en: "Kapa development en"
  idpconf_organisation_name_sv: "Kapa development sv"
  idpconf_organisation_displayname_fi: "Kapa development displ fi"
  idpconf_organisation_displayname_en: "Kapa development displ en"
  idpconf_organisation_displayname_sv: "Kapa development displ sv"
  idpconf_contact_given_name: "Kapa development"
  idpconf_contact_surname: "Kapa development"
  idpconf_contact_email: "admin@docker.dev"
  idpconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ ext_router_host }}"
#Common certs, keys
#Shibboleth cert and metadata generation
  shibgen_idp_id: "pub_mobileidp"
#Mobile plugin
  mobile_plugin_subject: "OU=Kapapub, O=Kapapub, L=Helsinki, ST=Uusimaa, C=FI, CN=kapa-mobile-plugin-dev"
#Mobile backend
  mobile_backend_subject: "OU=Kapapub, O=Kapapub, L=Helsinki, ST=Uusimaa, C=FI, CN=kapa-mobile-backend-dev"
  mobile_backend_mssap_host: "mssav.elisa.fi"
  mobile_backend_mssapid: "http://mss.elisa.fi/mssURI/asiakastesti"
  mobile_backend_msssignatureurl: "https://mssav.elisa.fi/MSSP/SOAP/MSS_Signature"
  mobile_backend_msspstatusurl: "https://mssav.elisa.fi/MSSP/SOAP/MSS_StatusPort"
  mobile_backend_msspreceipturl: "https://mssav.elisa.fi/MSSP/SOAP/MSS_ReceiptPort"
  mobile_backend_keystorepath: "/usr/share/tomcat/properties/mobile-backend-keystore"
  mobile_backend_etsi_customer_ca_file: ""
  mobile_backend_signed_cert_file: "mobile-backend.crt"

