  proxy_active_sessions_ttl_min: '40'
  proxy_failed_sessions_ttl_min: '10'
  metadata_rest_url: 'https://{{ int_router_host }}:{{ int_router_port }}/metadata'
  attribute_map_file: '/opt/proxy-server-properties/saml-attribute-map.csv'
  legacy_attribute_map_file: '/opt/proxy-server-properties/saml-legacy-attribute-map.csv'
  xroad_username: 'TBD'
  xroad_password: 'TBD'
  xroad_soso_name: 'TBD'
  xroad_secure_server_url: 'TBD'
  xroad_service_uri: 'TBD'
  xroad_user_id: 'TBD'
  xroad_consumer_id: 'TBD'
  xroad_producer_id: 'TBD'
  vtj_client_url: 'https://{{ int_router_host }}:{{ int_router_port }}'
  vtj_client_dummydata: 'true'
  satu_issuer_delimiter: "E_ID_VRK"
