  failure_redirect_url: 'https://{{ ext_router_host }}/sp-error'
  entity_id: 'https://{{ ext_router_host }}/sp2'
  spconf_host: '{{ ext_router_host }}'
  spconf_support_email: 'admin@tunnistaminen.test'
  spconf_service_idp_metadata_url: 'https://{{ int_router_host }}:{{ int_router_port }}/static/metadata/service-idp-metadata.xml'
  sp_key: 'sp-key.pem'
  sp_cert: 'sp-cert.pem'
  spconf_entityid_katso_pwd: "https://htesti.katso.tunnistus.fi/uas"
  spconf_location_katso_pwd: "/LoginKatsoPWD"
  spconf_AuthnContextDeclRef_katso_pwd: "https://htesti.katso.tunnistus.fi/uas/saml2/names/ac/password.katso.1"
  spconf_location_katso_otp: "/LoginKatsoOTP"
  spconf_AuthnContextDeclRef_katso_otp: "https://htesti.katso.tunnistus.fi/uas/saml2/names/ac/otp.katso.1"
  spconf_location_fakevetuma: "/LoginFakevetuma"
  spconf_entityid_fakevetuma: "https://shib-idp.kapa.ware.fi/idp/shibboleth"
  spconf_location_vrk: "/LoginVrk"
  spconf_entityid_vrk: "https://kortti.tunnistaminen.test/hstidp/idp1"
  spconf_location_mobiili: "/LoginMobiili"
  spconf_entityid_mobiili: "https://tunnistaminen.test/mobileidp/idp1"
  spconf_location_vetuma: "/LoginVetuma"
  spconf_entityid_vetuma: "https://testitunnistus.suomi.fi/VETUMASSO/app"
  spconf_location_nordea: "/LoginNordea"
  spconf_AuthnContextDeclRef_nordea: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.nordea.3"
  spconf_location_osuuspankki: "/LoginOsuuspankki"
  spconf_AuthnContextDeclRef_osuuspankki: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.oko.3"
  spconf_location_alandsbanken: "/LoginAlandsbanken"
  spconf_AuthnContextDeclRef_alandsbanken: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.alandsbanken.3"
  spconf_location_handelsbanken: "/LoginHandelsbanken"
  spconf_AuthnContextDeclRef_handelsbanken: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.handelsbanken.3"
  spconf_location_spankki: "/LoginSpankki"
  spconf_AuthnContextDeclRef_spankki: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.s-pankki.3"
  spconf_location_aktia: "/LoginAktia"
  spconf_AuthnContextDeclRef_aktia: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.aktia.3"
  spconf_location_pop: "/LoginPoppankki"
  spconf_AuthnContextDeclRef_pop: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.pop.3"
  spconf_location_saastopankki: "/LoginSaastopankki"
  spconf_AuthnContextDeclRef_saastopankki: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.saastopankki.3"
  spconf_location_omasaastopankki: "/LoginOmasaastopankki"
  spconf_AuthnContextDeclRef_omasaastopankki: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.omasaastopankki.3"
  spconf_location_danske_bank: "/LoginDanske-bank"
  spconf_AuthnContextDeclRef_danske_bank: "https://www.tunnistus.fi/ubitp/saml2/names/ac/tupas.sampo.3"
  spconf_integrationidp_entityid: "https://tunnistaminen.test/tupasidp2"
  spconf_location_mpass: "/LoginMPASS"
  spconf_entityid_mpass: "https://mpass.apro.tunnistus.fi/idp/shibboleth"
  spconf_status_acl: "127.0.0.1"
  apache_ciphers: "-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA"
  apache_server_name: 'https://{{ ext_router_host }}:{{ ext_router_port }}'
  success_redirect_url: 'https://{{ ext_router_host }}'
  spconf_scope: "{{ ext_router_host }}"
  spconf_entityid: "https://tunnistaminen.test/sp2"
  spconf_displayname: "KaPA DEV SP"
  spconf_displayname_fi: "KaPA DEV SP fi"
  spconf_displayname_en: "KaPA DEV SP en"
  spconf_displayname_sv: "KaPA DEV SP sv"
  spconf_description: "KaPA DEV SP"
  spconf_description_fi: "KaPA DEV SP desc fi"
  spconf_description_en: "KaPA DEV SP desc en"
  spconf_description_sv: "KaPA DEV SP desc sv"
  spconf_organisation_name: "KaPA e-identification development"
  spconf_organisation_name_fi: "KaPA e-identification development fi"
  spconf_organisation_name_en: "KaPA e-identification development en"
  spconf_organisation_name_sv: "KaPA e-identification development sv"
  spconf_organisation_displayname_fi: "KaPA e-identification development desc fi"
  spconf_organisation_displayname_en: "KaPA e-identification development desc en"
  spconf_organisation_displayname_sv: "KaPA e-identification development desc sv"
  spconf_organisation_url: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_fi: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_en: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_sv: "http://vm.fi/palveluarkkitehtuuri"
  spconf_contact_given_name: "KaPA e-identification development"
  spconf_contact_surname: "KaPA e-identification development"
  spconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ ext_router_host }}"
  spconf_kapa_image_url: "https://{{ ext_router_host }}/static/img/kapa.png"
  spconf_logo_height: "70"
  spconf_logo_width: "229"
  spconf_contact_email: 'admin@tunnistaminen.test'
  shibgen_sp_id: "pub_core_sp"
