  apache_ciphers: "-ALL:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA"
  entity_id: 'https://testipalvelu.test/sp'
  spconf_entityid: 'https://testipalvelu.test/sp'
  sp_key: 'testsp-key.pem'
  sp_cert: 'testsp-cert.pem'
  sp_apache_server_name: 'https://{{ spconf_host }}'
  spconf_host: 'testipalvelu.test'
  spconf_status_acl: "127.0.0.1"
  spconf_service_idp_metadata_url: 'https://tunnistaminen.test/static/metadata/idp-metadata.xml'
  spconf_service_idp_entityid: 'https://tunnistaminen.test/idp2'
  spconf_scope: "{{ spconf_host }}"
  spconf_displayname: "Testipalvelu"
  spconf_displayname_fi: "Testipalvelu"
  spconf_displayname_en: "Test service"
  spconf_displayname_sv: "Testservice"
  spconf_description: "Testipalvelu."
  spconf_description_fi: "Testipalvelu."
  spconf_description_en: "Test service."
  spconf_description_sv: "Testservice."
  spconf_organisation_name: "KaPA e-identification development"
  spconf_organisation_name_fi: "KaPA e-identification development fi"
  spconf_organisation_name_en: "KaPA e-identification development en"
  spconf_organisation_name_sv: "KaPA e-identification development sv"
  spconf_organisation_displayname_fi: "KaPA e-identification development desc fi"
  spconf_organisation_displayname_en: "KaPA e-identification development desc en"
  spconf_organisation_displayname_sv: "KaPA e-identification development desc sv"
  spconf_organisation_url: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_fi: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_en: "http://vm.fi/palveluarkkitehtuuri"
  spconf_organisation_url_sv: "http://vm.fi/palveluarkkitehtuuri"
  spconf_contact_given_name: "KaPA e-identification development"
  spconf_contact_surname: "KaPA e-identification development"
  spconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ spconf_host }}"
  spconf_kapa_image_url: "https://{{ spconf_host }}/static/img/kapa.png"
  spconf_logo_height: "70"
  spconf_logo_width: "229"
  spconf_contact_email: 'admin@testipalvelu.test'
  shibgen_sp_id: "pub_test_service"
  login_id_prefix: "LoginKAPA"
