---
#Common
#Tupas IdP
  tupas_properties_file: '/opt/tupas-identity-provider/tupas-bank-properties.csv'
  tupas_template_file: '/opt/tupas-identity-provider/tupas-html-form-template.html'
  idpconf_access_allowed_ip_range: "\"#{ {'192.168.0.1/32', '::1/128'} }\""
  idpconf_authproxy_idp_metadata_url: 'https://{{ int_router_host }}:{{ int_router_port }}/static/metadata/shibboleth-idp.kapa.dev.xml'
  idpconf_entityid: 'https://tunnistaminen.test/tupasidp2'
  idpconf_displayname: "KaPA dev integration IdP"
  idpconf_displayname_fi: "KaPA DEV integration IdP fi"
  idpconf_displayname_en: "KaPA DEV integration IdP en"
  idpconf_displayname_sv: "KaPA DEV integration IdP sv"
  idpconf_description: "KaPA DEV integration IdP"
  idpconf_description_fi: "KaPA DEV integration IdP desc fi"
  idpconf_description_en: "KaPA DEV integration IdP desc en"
  idpconf_description_sv: "KaPA DEV integration IdP desc sv"
  idpconf_kapa_image_url: "https://{{ ext_router_host }}/img/kapa.png"
  idpconf_organisation_name: "Kapa KaPA development"
  idpconf_organisation_name_fi: "KaPA development fi"
  idpconf_organisation_name_en: "KaPA development en"
  idpconf_organisation_name_sv: "KaPA development sv"
  idpconf_organisation_displayname_fi: "KaPA development displ fi"
  idpconf_organisation_displayname_en: "KaPA development displ en"
  idpconf_organisation_displayname_sv: "KaPA development displ sv"
  idpconf_contact_given_name: "KaPA development"
  idpconf_contact_surname: "KaPA development"
  idpconf_contact_email: "admin@tunnistaminen.test"
  idpconf_subj: "/C=FI/ST=Uusimaa/L=Helsinki/O=Kapapub/OU=Kapapub/CN={{ ext_router_host }}"
  idpconf_idp_shibboleth_error_tag: 'tupasidpshib'
  idpconf_idp_tomcat_error_tag: 'tupasidptc'
#Common certs, keys
#Shibboleth cert and metadata generation
  shibgen_idp_id: "pub_tupasidp"
  
