---
  vartti_api_host: 'varttiservice.test'
  vartti_url: 'https://{{ vartti_api_host }}/api'
  vartti_application_name: 'FooBar'
  vartti_role_name: 'FooBar'
  vartti_keystore: 'vartti-client-pub.jks'
  vartti_truststore: 'vartti-client-pub-truststore.jks'
  vartti_api_logging: 'true'
  vartti_client_dummydata: 'true'
  vartti_client_dummydata_hetu: '210281-9988'
