---
#Common
  tomcat_alias: "tun-pub-cache1"

#Vtjclient
  vtj_ca: 'VRK CA for Test Purposes'
  xroad_endpoint: 'http://{{ fake_vtj_host }}:{{ fake_vtj_port2 }}/'
  xroad_connectivity_keystore_path: '/data00/deploy/vtjcertstore.jks'
  service_sdsb_instance: 'FI-DEV'
  service_subsystem_code: 'VTJService'
  client_sdsb_instance: 'FI-DEV'
  client_subsystem_code: 'APROClient'

# Testing
  vtj_dummydata: 'false'
  vtj_dummydata_hetu: '010191-9630'
  vtj_dummydata_sleep: '600'
